spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/companydb}
      auto-index-creation: ${MONGO_AUTO_INDEX:true}
  application:
    name: ${APP_NAME:company-service}
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: company-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.microservices.user.model.dto,*"
        spring.json.value.default.type: "java.util.HashMap"
        spring.json.use.type.headers: false

server:
  port: ${SERVER_PORT:8081}  # Different port from user-service

mongock:
  migration-scan-package:
    - com.microservices.company.migrations
  fail-fast: true
  change-log-collection-name: mongockChangeLog
  lock-collection-name: mongockLock
